export const LANGS = [
  { id: "tr", native: "Türkçe", locale: "tr-TR" },
  { id: "en", native: "English", locale: "en-US" },
  { id: "de", native: "Deutsch", locale: "de-DE" },
  { id: "es", native: "Español", locale: "es-ES" },
  { id: "fr", native: "Français", locale: "fr-FR" },
  { id: "it", native: "Italiano", locale: "it-IT" },
  { id: "pt", native: "Português", locale: "pt-BR" },
  { id: "ru", native: "Русский", locale: "ru-RU" },
] as const;

export type Lang = (typeof LANGS)[number]["id"];

export function localeOf(lang: Lang) {
  return LANGS.find((l) => l.id === lang)?.locale ?? "en-US";
}

export function isLang(v: string): v is Lang {
  return LANGS.some((l) => l.id === v);
}

type Dict = {
  brand: string;
  kicker: string;
  heroTitle: string;
  heroTagline: string;
  heroBody: string;
  chainBadge: string;
  chainHint: string;
  whatHq: string;
  whatHqBody: string;
  whatKai: string;
  whatKaiBody: string;
  whyToken: string;
  whyTokenBody: string;
  utilityTitle: string;
  utilityLead: string;
  util1: string;
  util2: string;
  util3: string;
  util4: string;
  proofTitle: string;
  proof1: string;
  proof2: string;
  proof3: string;
  proof4: string;
  roadmap: string;
  rmNow: string;
  rmNowD: string;
  rmNext: string;
  rmNextD: string;
  rmThen: string;
  rmThenD: string;
  rmLater: string;
  rmLaterD: string;
  buyCta: string;
  connect: string;
  amount: string;
  est: string;
  unit: string;
  payWith: string;
  approve: string;
  buy: string;
  buying: string;
  swapBuy: string;
  swapping: string;
  bridging: string;
  swapUniswap: string;
  openUniswap: string;
  saleWait: string;
  saleWaitHint: string;
  saleClosed: string;
  belowMin: string;
  noWallet: string;
  usdgBal: string;
  payBal: string;
  yourBought: string;
  cap: string;
  txOk: string;
  txFail: string;
  needBal: string;
  rounds: string;
  roundsLead: string;
  tokenomics: string;
  supply: string;
  supplyLine: string;
  how: string;
  step1: string;
  step1d: string;
  step2: string;
  step2d: string;
  step3: string;
  step3d: string;
  product: string;
  open: string;
  pending: string;
  everyone: string;
  tge: string;
  teamVest: string;
  contracts: string;
  overview: string;
  footerChain: string;
  allocPresale: string;
  allocEco: string;
  allocTreasury: string;
  allocLiquidity: string;
  allocMarketing: string;
  allocTeam: string;
  allocCommunity: string;
  allocAdvisors: string;
};

export const copy: Record<Lang, Dict> = {
  tr: {
    brand: "KindredHQ",
    kicker: "KAI ön satış",
    heroTitle: "Yüzler değil, ruhlar tanışsın.",
    heroTagline: "KindredHQ yardımcı tokenı — Robinhood Chain üzerinde.",
    heroBody:
      "KindredHQ fotoğrafsız bir tanışma ürünüdür ve yayındadır. Kai sohbetle tanır. $KAI spekülasyon aracı değil; Kai kredileri, premium katman ve ekosistem erişimi için bir kullanım tokenıdır.",
    chainBadge: "Robinhood Chain · 4663",
    chainHint:
      "KAI bir Robinhood Chain (4663) ERC-20’sidir. Gaz ETH, mutabakat USDG. Başka ağdaki tokenlar önce bu zincire gelir.",
    whatHq: "KindredHQ nedir?",
    whatHqBody:
      "Fotoğrafsız tanışma. İnsanları görünüşle değil kim olduklarıyla eşleştirir. Her seferinde tek eşleşme.",
    whatKai: "Kai nedir?",
    whatKaiBody:
      "Sohbetle tanıyan yapay zeka rehberi. Anket değil; ürünün üzerine kurulduğu katman.",
    whyToken: "$KAI neden var?",
    whyTokenBody:
      "Ekosistemin fayda katmanı. Kullanıcı kripto bilmek zorunda değil: ödeme → Kai Kredisi → hizmet. Hisse veya gelir hakkı değildir.",
    utilityTitle: "Ekosistemde ne işe yarar",
    utilityLead:
      "Arz sabit. Token, ürünü çalıştırmak için vardır — vaat edilen getiri için değil.",
    util1: "Kai Kredileri — sohbet ve eşleşme erişimi.",
    util2: "Premium Kai — daha derin uyum içgörüsü.",
    util3: "Ekosistem ödülleri — davet ve katkı.",
    util4: "İş ortakları — Kai’ye bağlanan hizmetler.",
    proofTitle: "Ürün şu an",
    proof1: "Platform yayında",
    proof2: "Kai sohbeti canlı",
    proof3: "Eşleştirme çalışıyor",
    proof4: "Kademeli açılma",
    roadmap: "Yol haritası",
    rmNow: "Şimdi — KAI Match",
    rmNowD: "Uyum · sohbetle tanıma · tek eşleşme",
    rmNext: "Sırada",
    rmNextD: "Kai Kredileri · büyüme · mobil",
    rmThen: "Ardından — KAI Relationship",
    rmThenD: "İlişki içgörüsü · iletişim desteği",
    rmLater: "Sonra — KAI Self · Life",
    rmLaterD: "Kişisel içgörü · esenlik · yaşam araçları",
    buyCta: "KAI al",
    connect: "Cüzdan bağla",
    amount: "Kaç KAI almak istiyorsun?",
    est: "Tahmini ödeme",
    unit: "Birim fiyat",
    payWith: "Öde",
    approve: "USDG onayla",
    buy: "Satın al",
    buying: "Cüzdanda onayla…",
    swapBuy: "Çevir ve al",
    swapping: "USDG’ye çevriliyor…",
    bridging: "Köprü tamamlanıyor…",
    swapUniswap:
      "ETH otomatik çeviri zincirde düşüyor. MetaMask Takas veya Uniswap ile ETH→USDG yap, sonra USDG ile al.",
    openUniswap: "Uniswap’te ETH → USDG",
    saleWait: "Zincir onayı bekleniyor",
    saleWaitHint: "Satış zincirde açık.",
    saleClosed: "Satış kapandı",
    belowMin: "En az 1 $ karşılığı alım yapılabilir.",
    noWallet: "Tarayıcıda cüzdan bulunamadı. MetaMask yükle.",
    usdgBal: "USDG bakiyen",
    payBal: "Seçilen varlık",
    yourBought: "Bu cüzdandan alınan",
    cap: "Cüzdan tavanı",
    txOk: "Alım kaydedildi. KAI TGE’de cüzdana gelir.",
    txFail: "İşlem başarısız veya reddedildi",
    needBal: "Bu varlıkta yeterli bakiye yok",
    rounds: "Turlar",
    roundsLead: "Dört tur, fiyat sabit. Dilimler kendi tur fiyatından hesaplanır.",
    tokenomics: "Token ekonomisi",
    supply: "Toplam arz sabit",
    supplyLine: "Ön satış tavanı kontratta kilitli.",
    how: "Nasıl alınır",
    step1: "Cüzdanını bağla",
    step1d: "MetaMask. Ağ: Robinhood Chain (4663).",
    step2: "USDG ile al",
    step2d: "Robinhood’da USDG varsa doğrudan al. ETH’yi Takas ile USDG yap.",
    step3: "Miktarı yaz ve imzala",
    step3d: "Onay + alım senin cüzdanında. Minimum 1 $.",
    product: "KindredHQ.io",
    open: "Satış açık",
    pending: "Bekleniyor",
    everyone: "Herkes katılabilir",
    tge: "TGE’de %15 açılır, kalanı 18 ay doğrusal.",
    teamVest: "Ekip: TGE %0, 12 ay bekler, 60 ay doğrusal.",
    contracts: "Kontratlar",
    overview: "Genel bakış",
    footerChain: "Robinhood Chain üzerinde yayımlanır.",
    allocPresale: "Ön satış",
    allocEco: "Ekosistem ve Kai ödülleri",
    allocTreasury: "Hazine / ürün",
    allocLiquidity: "Likidite",
    allocMarketing: "Pazarlama",
    allocTeam: "Ekip",
    allocCommunity: "Topluluk",
    allocAdvisors: "Danışmanlar",
  },
  en: {
    brand: "KindredHQ",
    kicker: "KAI presale",
    heroTitle: "Let souls meet, not faces.",
    heroTagline: "KindredHQ’s utility token — on Robinhood Chain.",
    heroBody:
      "KindredHQ is a live, photo-free matching product. Kai learns you through conversation. $KAI is not a speculative wrapper; it pays for Kai Credits, premium access, and ecosystem services.",
    chainBadge: "Robinhood Chain · 4663",
    chainHint:
      "KAI is an ERC-20 on Robinhood Chain (4663). Gas is ETH. Settlement is USDG. Assets on other networks arrive here first.",
    whatHq: "What is KindredHQ?",
    whatHqBody:
      "Photo-free matching. People meet for who they are. One match at a time.",
    whatKai: "What is Kai?",
    whatKaiBody: "An AI guide that learns you through chat — the layer the product is built on.",
    whyToken: "Why $KAI?",
    whyTokenBody:
      "The utility layer of the ecosystem. Users need not know crypto: pay → Kai Credits → use the product. Not equity or a claim on revenue.",
    utilityTitle: "What it does in the ecosystem",
    utilityLead: "Supply is fixed. The token exists to run the product — not to promise yield.",
    util1: "Kai Credits — chat and matching access.",
    util2: "Premium Kai — deeper compatibility insight.",
    util3: "Ecosystem rewards — invites and contribution.",
    util4: "Partners — services that plug into Kai.",
    proofTitle: "The product today",
    proof1: "Platform is live",
    proof2: "Kai chat is live",
    proof3: "Matching is running",
    proof4: "Gradual unlock",
    roadmap: "Roadmap",
    rmNow: "Now — KAI Match",
    rmNowD: "Compatibility · conversation · one match",
    rmNext: "Next",
    rmNextD: "Kai Credits · growth · mobile",
    rmThen: "Then — KAI Relationship",
    rmThenD: "Relationship insight · communication support",
    rmLater: "Later — KAI Self · Life",
    rmLaterD: "Personal insight · wellbeing · life tools",
    buyCta: "Buy KAI",
    connect: "Connect wallet",
    amount: "How much KAI do you want?",
    est: "Estimated payment",
    unit: "Unit price",
    payWith: "Pay with",
    approve: "Approve USDG",
    buy: "Buy",
    buying: "Confirm in wallet…",
    swapBuy: "Swap and buy",
    swapping: "Swapping to USDG…",
    bridging: "Bridge in progress…",
    swapUniswap:
      "Automatic ETH swap is reverting on-chain. Use MetaMask Swap or Uniswap (ETH→USDG), then buy with USDG.",
    openUniswap: "ETH → USDG on Uniswap",
    saleWait: "Waiting on-chain",
    saleWaitHint: "The sale is open on-chain.",
    saleClosed: "Sale closed",
    belowMin: "Minimum purchase is $1 equivalent.",
    noWallet: "No wallet found. Install MetaMask.",
    usdgBal: "USDG balance",
    payBal: "Selected asset",
    yourBought: "Bought from this wallet",
    cap: "Wallet cap",
    txOk: "Purchase recorded. KAI arrives in-wallet at TGE.",
    txFail: "Transaction failed or rejected",
    needBal: "Not enough balance in this asset",
    rounds: "Rounds",
    roundsLead: "Four rounds at fixed prices. Each tranche uses its own round price.",
    tokenomics: "Token economics",
    supply: "Total supply is fixed",
    supplyLine: "The presale cap is locked in the contract.",
    how: "How to buy",
    step1: "Connect a wallet",
    step1d: "MetaMask. Network: Robinhood Chain (4663).",
    step2: "Pay with USDG",
    step2d: "If you hold USDG on Robinhood, buy directly. Swap ETH→USDG in MetaMask first.",
    step3: "Enter an amount and sign",
    step3d: "Approve + buy in your wallet. Minimum $1.",
    product: "KindredHQ.io",
    open: "Sale open",
    pending: "Pending",
    everyone: "Open to everyone",
    tge: "15% at TGE, remainder linear over 18 months.",
    teamVest: "Team: 0% at TGE, 12-month cliff, 60 months linear.",
    contracts: "Contracts",
    overview: "Overview",
    footerChain: "Issued on Robinhood Chain.",
    allocPresale: "Presale",
    allocEco: "Ecosystem & Kai rewards",
    allocTreasury: "Treasury / product",
    allocLiquidity: "Liquidity",
    allocMarketing: "Marketing",
    allocTeam: "Team",
    allocCommunity: "Community",
    allocAdvisors: "Advisors",
  },
  de: {
    brand: "KindredHQ",
    kicker: "KAI-Vorverkauf",
    heroTitle: "Seelen begegnen sich, nicht Gesichter.",
    heroTagline: "Utility-Token von KindredHQ — auf Robinhood Chain.",
    heroBody:
      "KindredHQ ist ein live, fotofreies Matching-Produkt. Kai lernt dich im Gespräch. $KAI ist kein Spekulationshülle, sondern zahlt Kai-Credits, Premium-Zugang und Ökosystem-Dienste.",
    chainBadge: "Robinhood Chain · 4663",
    chainHint:
      "KAI ist ein ERC-20 auf Robinhood Chain (4663). Gas ist ETH, Abrechnung USDG. Token anderer Netze kommen zuerst hier an.",
    whatHq: "Was ist KindredHQ?",
    whatHqBody: "Fotofreies Matching. Menschen treffen sich wegen wer sie sind. Ein Match nach dem anderen.",
    whatKai: "Was ist Kai?",
    whatKaiBody: "Ein KI-Guide, der dich im Chat kennt — die Schicht, auf der das Produkt steht.",
    whyToken: "Warum $KAI?",
    whyTokenBody:
      "Die Nutzschicht des Ökosystems. Nutzer müssen kein Krypto kennen: zahlen → Kai-Credits → Produkt nutzen. Keine Aktie, kein Ertragsanspruch.",
    utilityTitle: "Rolle im Ökosystem",
    utilityLead: "Angebot ist fest. Der Token betreibt das Produkt — er verspricht keine Rendite.",
    util1: "Kai-Credits — Chat- und Matching-Zugang.",
    util2: "Premium-Kai — tiefere Kompatibilität.",
    util3: "Ökosystem-Belohnungen — Einladungen und Beitrag.",
    util4: "Partner — Dienste, die an Kai anbinden.",
    proofTitle: "Das Produkt heute",
    proof1: "Plattform live",
    proof2: "Kai-Chat live",
    proof3: "Matching läuft",
    proof4: "Stufenweise Freischaltung",
    roadmap: "Fahrplan",
    rmNow: "Jetzt — KAI Match",
    rmNowD: "Kompatibilität · Gespräch · ein Match",
    rmNext: "Als Nächstes",
    rmNextD: "Kai-Credits · Wachstum · Mobil",
    rmThen: "Danach — KAI Relationship",
    rmThenD: "Beziehungs-Einblick · Kommunikation",
    rmLater: "Später — KAI Self · Life",
    rmLaterD: "Persönlicher Einblick · Wohlbefinden",
    buyCta: "KAI kaufen",
    connect: "Wallet verbinden",
    amount: "Wie viel KAI möchtest du?",
    est: "Geschätzte Zahlung",
    unit: "Stückpreis",
    payWith: "Zahlen mit",
    approve: "USDG genehmigen",
    buy: "Kaufen",
    buying: "In der Wallet bestätigen…",
    swapBuy: "Tauschen und kaufen",
    swapping: "Wird zu USDG getauscht…",
    bridging: "Brücke läuft…",
    swapUniswap:
      "Automatischer ETH-Tausch schlägt on-chain fehl. ETH→USDG in MetaMask Swap oder Uniswap, dann mit USDG kaufen.",
    openUniswap: "ETH → USDG auf Uniswap",
    saleWait: "Warte auf die Chain",
    saleWaitHint: "Der Verkauf ist on-chain offen.",
    saleClosed: "Verkauf geschlossen",
    belowMin: "Mindestkauf entspricht 1 $.",
    noWallet: "Keine Wallet gefunden. MetaMask installieren.",
    usdgBal: "USDG-Saldo",
    payBal: "Gewählter Vermögenswert",
    yourBought: "Von dieser Wallet gekauft",
    cap: "Wallet-Obergrenze",
    txOk: "Kauf erfasst. KAI kommt zum TGE in die Wallet.",
    txFail: "Transaktion fehlgeschlagen oder abgelehnt",
    needBal: "Nicht genug Saldo in diesem Asset",
    rounds: "Runden",
    roundsLead: "Vier Runden mit festen Preisen. Jede Tranche nutzt den Preis ihrer Runde.",
    tokenomics: "Token-Ökonomie",
    supply: "Gesamtangebot fest",
    supplyLine: "Die Vorverkaufsgrenze ist im Vertrag gesperrt.",
    how: "So kaufst du",
    step1: "Wallet verbinden",
    step1d: "MetaMask. Netz: Robinhood Chain (4663).",
    step2: "Mit USDG zahlen",
    step2d: "USDG auf Robinhood? Direkt kaufen. ETH zuerst zu USDG tauschen.",
    step3: "Betrag eingeben und signieren",
    step3d: "Genehmigen + kaufen in deiner Wallet. Minimum 1 $.",
    product: "KindredHQ.io",
    open: "Verkauf offen",
    pending: "Ausstehend",
    everyone: "Für alle offen",
    tge: "15 % beim TGE, Rest linear über 18 Monate.",
    teamVest: "Team: 0 % TGE, 12 Monate Cliff, 60 Monate linear.",
    contracts: "Verträge",
    overview: "Überblick",
    footerChain: "Herausgegeben auf Robinhood Chain.",
    allocPresale: "Vorverkauf",
    allocEco: "Ökosystem & Kai-Belohnungen",
    allocTreasury: "Treasury / Produkt",
    allocLiquidity: "Liquidität",
    allocMarketing: "Marketing",
    allocTeam: "Team",
    allocCommunity: "Community",
    allocAdvisors: "Berater",
  },
  es: {
    brand: "KindredHQ",
    kicker: "Preventa KAI",
    heroTitle: "Que se encuentren las almas, no las caras.",
    heroTagline: "Token de utilidad de KindredHQ — en Robinhood Chain.",
    heroBody:
      "KindredHQ es un producto de matching en vivo, sin fotos. Kai te conoce en conversación. $KAI no es un envoltorio especulativo: paga créditos Kai, acceso premium y servicios del ecosistema.",
    chainBadge: "Robinhood Chain · 4663",
    chainHint:
      "KAI es un ERC-20 en Robinhood Chain (4663). El gas es ETH; la liquidación, USDG. Los activos de otras redes llegan aquí primero.",
    whatHq: "¿Qué es KindredHQ?",
    whatHqBody: "Matching sin fotos. La gente se encuentra por quién es. Un match cada vez.",
    whatKai: "¿Qué es Kai?",
    whatKaiBody: "Una guía de IA que te conoce por el chat: la capa sobre la que se construye el producto.",
    whyToken: "¿Por qué $KAI?",
    whyTokenBody:
      "La capa de utilidad del ecosistema. No hace falta saber cripto: pagar → créditos Kai → usar el producto. No es capital ni derecho a ingresos.",
    utilityTitle: "Qué hace en el ecosistema",
    utilityLead: "La oferta es fija. El token existe para operar el producto, no para prometer rendimiento.",
    util1: "Créditos Kai — chat y matching.",
    util2: "Kai premium — compatibilidad más profunda.",
    util3: "Recompensas del ecosistema — invitaciones y aporte.",
    util4: "Socios — servicios conectados a Kai.",
    proofTitle: "El producto hoy",
    proof1: "Plataforma en vivo",
    proof2: "Chat Kai en vivo",
    proof3: "Matching activo",
    proof4: "Apertura gradual",
    roadmap: "Hoja de ruta",
    rmNow: "Ahora — KAI Match",
    rmNowD: "Compatibilidad · conversación · un match",
    rmNext: "Siguiente",
    rmNextD: "Créditos Kai · crecimiento · móvil",
    rmThen: "Después — KAI Relationship",
    rmThenD: "Insight de relación · comunicación",
    rmLater: "Luego — KAI Self · Life",
    rmLaterD: "Insight personal · bienestar",
    buyCta: "Comprar KAI",
    connect: "Conectar cartera",
    amount: "¿Cuánto KAI quieres?",
    est: "Pago estimado",
    unit: "Precio unitario",
    payWith: "Pagar con",
    approve: "Aprobar USDG",
    buy: "Comprar",
    buying: "Confirma en la cartera…",
    swapBuy: "Convertir y comprar",
    swapping: "Convirtiendo a USDG…",
    bridging: "Puente en curso…",
    swapUniswap:
      "El swap automático de ETH revierte en cadena. Usa MetaMask Swap o Uniswap (ETH→USDG) y compra con USDG.",
    openUniswap: "ETH → USDG en Uniswap",
    saleWait: "Esperando la cadena",
    saleWaitHint: "La venta está abierta en cadena.",
    saleClosed: "Venta cerrada",
    belowMin: "La compra mínima equivale a 1 $.",
    noWallet: "No hay cartera. Instala MetaMask.",
    usdgBal: "Saldo USDG",
    payBal: "Activo elegido",
    yourBought: "Comprado desde esta cartera",
    cap: "Tope por cartera",
    txOk: "Compra registrada. KAI llega a la cartera en el TGE.",
    txFail: "Transacción fallida o rechazada",
    needBal: "Saldo insuficiente en este activo",
    rounds: "Rondas",
    roundsLead: "Cuatro rondas a precio fijo. Cada tramo usa el precio de su ronda.",
    tokenomics: "Tokenómica",
    supply: "Oferta total fija",
    supplyLine: "El tope de preventa está bloqueado en el contrato.",
    how: "Cómo comprar",
    step1: "Conecta una cartera",
    step1d: "MetaMask. Red: Robinhood Chain (4663).",
    step2: "Paga con USDG",
    step2d: "Si tienes USDG en Robinhood, compra directo. Cambia ETH→USDG antes.",
    step3: "Escribe la cantidad y firma",
    step3d: "Aprobar + comprar en tu cartera. Mínimo 1 $.",
    product: "KindredHQ.io",
    open: "Venta abierta",
    pending: "Pendiente",
    everyone: "Abierto a todos",
    tge: "15 % en el TGE; el resto lineal en 18 meses.",
    teamVest: "Equipo: 0 % TGE, 12 meses de cliff, 60 meses lineal.",
    contracts: "Contratos",
    overview: "Resumen",
    footerChain: "Emitido en Robinhood Chain.",
    allocPresale: "Preventa",
    allocEco: "Ecosistema y recompensas Kai",
    allocTreasury: "Tesorería / producto",
    allocLiquidity: "Liquidez",
    allocMarketing: "Marketing",
    allocTeam: "Equipo",
    allocCommunity: "Comunidad",
    allocAdvisors: "Asesores",
  },
  fr: {
    brand: "KindredHQ",
    kicker: "Prévente KAI",
    heroTitle: "Que les âmes se rencontrent, pas les visages.",
    heroTagline: "Jeton d’utilité KindredHQ — sur Robinhood Chain.",
    heroBody:
      "KindredHQ est un produit de matching live, sans photos. Kai vous apprend par la conversation. $KAI n’est pas une enveloppe spéculative : il paie les crédits Kai, l’accès premium et les services de l’écosystème.",
    chainBadge: "Robinhood Chain · 4663",
    chainHint:
      "KAI est un ERC-20 sur Robinhood Chain (4663). Le gaz est l’ETH ; le règlement, l’USDG. Les actifs des autres réseaux arrivent ici d’abord.",
    whatHq: "Qu’est-ce que KindredHQ ?",
    whatHqBody: "Matching sans photos. On se rencontre pour qui l’on est. Un match à la fois.",
    whatKai: "Qu’est-ce que Kai ?",
    whatKaiBody: "Un guide IA qui vous connaît par le chat — la couche sur laquelle le produit est bâti.",
    whyToken: "Pourquoi $KAI ?",
    whyTokenBody:
      "La couche d’utilité de l’écosystème. Pas besoin de connaître la crypto : payer → crédits Kai → utiliser le produit. Ni action, ni droit sur les revenus.",
    utilityTitle: "Rôle dans l’écosystème",
    utilityLead: "L’offre est fixe. Le jeton fait tourner le produit — il ne promet pas de rendement.",
    util1: "Crédits Kai — chat et matching.",
    util2: "Kai premium — compatibilité plus profonde.",
    util3: "Récompenses écosystème — invitations et contribution.",
    util4: "Partenaires — services branchés sur Kai.",
    proofTitle: "Le produit aujourd’hui",
    proof1: "Plateforme en ligne",
    proof2: "Chat Kai en ligne",
    proof3: "Matching actif",
    proof4: "Déblocage progressif",
    roadmap: "Feuille de route",
    rmNow: "Maintenant — KAI Match",
    rmNowD: "Compatibilité · conversation · un match",
    rmNext: "Ensuite",
    rmNextD: "Crédits Kai · croissance · mobile",
    rmThen: "Puis — KAI Relationship",
    rmThenD: "Insight relationnel · communication",
    rmLater: "Plus tard — KAI Self · Life",
    rmLaterD: "Insight personnel · bien-être",
    buyCta: "Acheter KAI",
    connect: "Connecter le portefeuille",
    amount: "Combien de KAI voulez-vous ?",
    est: "Paiement estimé",
    unit: "Prix unitaire",
    payWith: "Payer avec",
    approve: "Approuver l’USDG",
    buy: "Acheter",
    buying: "Confirmez dans le portefeuille…",
    swapBuy: "Convertir et acheter",
    swapping: "Conversion en USDG…",
    bridging: "Pont en cours…",
    swapUniswap:
      "Le swap ETH automatique revert on-chain. Utilisez MetaMask Swap ou Uniswap (ETH→USDG), puis achetez en USDG.",
    openUniswap: "ETH → USDG sur Uniswap",
    saleWait: "En attente de la chaîne",
    saleWaitHint: "La vente est ouverte on-chain.",
    saleClosed: "Vente close",
    belowMin: "Achat minimum équivalent à 1 $.",
    noWallet: "Aucun portefeuille. Installez MetaMask.",
    usdgBal: "Solde USDG",
    payBal: "Actif choisi",
    yourBought: "Acheté depuis ce portefeuille",
    cap: "Plafond par portefeuille",
    txOk: "Achat enregistré. Le KAI arrive au TGE.",
    txFail: "Transaction échouée ou refusée",
    needBal: "Solde insuffisant sur cet actif",
    rounds: "Tours",
    roundsLead: "Quatre tours à prix fixe. Chaque tranche utilise le prix de son tour.",
    tokenomics: "Tokenomics",
    supply: "Offre totale fixe",
    supplyLine: "Le plafond de prévente est verrouillé dans le contrat.",
    how: "Comment acheter",
    step1: "Connectez un portefeuille",
    step1d: "MetaMask. Réseau : Robinhood Chain (4663).",
    step2: "Payez en USDG",
    step2d: "USDG sur Robinhood ? Achetez directement. Convertissez d’abord ETH→USDG.",
    step3: "Saisissez le montant et signez",
    step3d: "Approuver + acheter dans votre portefeuille. Minimum 1 $.",
    product: "KindredHQ.io",
    open: "Vente ouverte",
    pending: "En attente",
    everyone: "Ouvert à tous",
    tge: "15 % au TGE, le reste linéaire sur 18 mois.",
    teamVest: "Équipe : 0 % TGE, cliff 12 mois, linéaire 60 mois.",
    contracts: "Contrats",
    overview: "Aperçu",
    footerChain: "Émis sur Robinhood Chain.",
    allocPresale: "Prévente",
    allocEco: "Écosystème et récompenses Kai",
    allocTreasury: "Trésorerie / produit",
    allocLiquidity: "Liquidité",
    allocMarketing: "Marketing",
    allocTeam: "Équipe",
    allocCommunity: "Communauté",
    allocAdvisors: "Conseillers",
  },
  it: {
    brand: "KindredHQ",
    kicker: "Prevendita KAI",
    heroTitle: "Si incontrino le anime, non i volti.",
    heroTagline: "Token di utilità KindredHQ — su Robinhood Chain.",
    heroBody:
      "KindredHQ è un prodotto di matching live, senza foto. Kai ti conosce conversando. $KAI non è un involucro speculativo: paga crediti Kai, accesso premium e servizi dell’ecosistema.",
    chainBadge: "Robinhood Chain · 4663",
    chainHint:
      "KAI è un ERC-20 su Robinhood Chain (4663). Il gas è ETH; il regolamento, USDG. Gli asset di altre reti arrivano prima qui.",
    whatHq: "Cos’è KindredHQ?",
    whatHqBody: "Matching senza foto. Ci si incontra per chi si è. Un match alla volta.",
    whatKai: "Cos’è Kai?",
    whatKaiBody: "Una guida IA che ti conosce in chat — lo strato su cui è costruito il prodotto.",
    whyToken: "Perché $KAI?",
    whyTokenBody:
      "Lo strato di utilità dell’ecosistema. Non serve conoscere il crypto: paga → crediti Kai → usa il prodotto. Non è equity né diritto sui ricavi.",
    utilityTitle: "Ruolo nell’ecosistema",
    utilityLead: "L’offerta è fissa. Il token fa funzionare il prodotto — non promette rendimento.",
    util1: "Crediti Kai — chat e matching.",
    util2: "Kai premium — compatibilità più profonda.",
    util3: "Ricompense ecosistema — inviti e contributo.",
    util4: "Partner — servizi collegati a Kai.",
    proofTitle: "Il prodotto oggi",
    proof1: "Piattaforma live",
    proof2: "Chat Kai live",
    proof3: "Matching attivo",
    proof4: "Sblocco graduale",
    roadmap: "Roadmap",
    rmNow: "Ora — KAI Match",
    rmNowD: "Compatibilità · conversazione · un match",
    rmNext: "Dopo",
    rmNextD: "Crediti Kai · crescita · mobile",
    rmThen: "Poi — KAI Relationship",
    rmThenD: "Insight relazionale · comunicazione",
    rmLater: "Più tardi — KAI Self · Life",
    rmLaterD: "Insight personale · benessere",
    buyCta: "Compra KAI",
    connect: "Collega il wallet",
    amount: "Quanti KAI vuoi?",
    est: "Pagamento stimato",
    unit: "Prezzo unitario",
    payWith: "Paga con",
    approve: "Approva USDG",
    buy: "Compra",
    buying: "Conferma nel wallet…",
    swapBuy: "Converti e compra",
    swapping: "Conversione in USDG…",
    bridging: "Bridge in corso…",
    swapUniswap:
      "Lo swap ETH automatico revert on-chain. Usa MetaMask Swap o Uniswap (ETH→USDG), poi compra con USDG.",
    openUniswap: "ETH → USDG su Uniswap",
    saleWait: "In attesa della chain",
    saleWaitHint: "La vendita è aperta on-chain.",
    saleClosed: "Vendita chiusa",
    belowMin: "Acquisto minimo equivalente a 1 $.",
    noWallet: "Nessun wallet. Installa MetaMask.",
    usdgBal: "Saldo USDG",
    payBal: "Asset selezionato",
    yourBought: "Acquistato da questo wallet",
    cap: "Cap per wallet",
    txOk: "Acquisto registrato. KAI arriva nel wallet al TGE.",
    txFail: "Transazione fallita o rifiutata",
    needBal: "Saldo insufficiente su questo asset",
    rounds: "Round",
    roundsLead: "Quattro round a prezzo fisso. Ogni trance usa il prezzo del proprio round.",
    tokenomics: "Tokenomics",
    supply: "Offerta totale fissa",
    supplyLine: "Il cap della prevendita è bloccato nel contratto.",
    how: "Come comprare",
    step1: "Collega un wallet",
    step1d: "MetaMask. Rete: Robinhood Chain (4663).",
    step2: "Paga con USDG",
    step2d: "USDG su Robinhood? Compra diretto. Prima scambia ETH→USDG.",
    step3: "Inserisci l’importo e firma",
    step3d: "Approva + compra nel tuo wallet. Minimo 1 $.",
    product: "KindredHQ.io",
    open: "Vendita aperta",
    pending: "In attesa",
    everyone: "Aperto a tutti",
    tge: "15 % al TGE, il resto lineare in 18 mesi.",
    teamVest: "Team: 0 % TGE, cliff 12 mesi, lineare 60 mesi.",
    contracts: "Contratti",
    overview: "Panoramica",
    footerChain: "Emesso su Robinhood Chain.",
    allocPresale: "Prevendita",
    allocEco: "Ecosistema e ricompense Kai",
    allocTreasury: "Tesoreria / prodotto",
    allocLiquidity: "Liquidità",
    allocMarketing: "Marketing",
    allocTeam: "Team",
    allocCommunity: "Community",
    allocAdvisors: "Advisor",
  },
  pt: {
    brand: "KindredHQ",
    kicker: "Pré-venda KAI",
    heroTitle: "Que as almas se encontrem, não os rostos.",
    heroTagline: "Token de utilidade da KindredHQ — na Robinhood Chain.",
    heroBody:
      "KindredHQ é um produto de matching ao vivo, sem fotos. Kai conhece você pela conversa. $KAI não é um envelope especulativo: paga créditos Kai, acesso premium e serviços do ecossistema.",
    chainBadge: "Robinhood Chain · 4663",
    chainHint:
      "KAI é um ERC-20 na Robinhood Chain (4663). O gás é ETH; a liquidação, USDG. Ativos de outras redes chegam aqui primeiro.",
    whatHq: "O que é a KindredHQ?",
    whatHqBody: "Matching sem fotos. Pessoas se encontram por quem são. Um match de cada vez.",
    whatKai: "O que é o Kai?",
    whatKaiBody: "Um guia de IA que te conhece no chat — a camada sobre a qual o produto é construído.",
    whyToken: "Por que $KAI?",
    whyTokenBody:
      "A camada de utilidade do ecossistema. Não é preciso saber cripto: pagar → créditos Kai → usar o produto. Não é equity nem direito a receita.",
    utilityTitle: "Papel no ecossistema",
    utilityLead: "A oferta é fixa. O token existe para operar o produto — não para prometer rendimento.",
    util1: "Créditos Kai — chat e matching.",
    util2: "Kai premium — compatibilidade mais profunda.",
    util3: "Recompensas do ecossistema — convites e contribuição.",
    util4: "Parceiros — serviços ligados ao Kai.",
    proofTitle: "O produto hoje",
    proof1: "Plataforma no ar",
    proof2: "Chat Kai no ar",
    proof3: "Matching ativo",
    proof4: "Desbloqueio gradual",
    roadmap: "Roteiro",
    rmNow: "Agora — KAI Match",
    rmNowD: "Compatibilidade · conversa · um match",
    rmNext: "Em seguida",
    rmNextD: "Créditos Kai · crescimento · mobile",
    rmThen: "Depois — KAI Relationship",
    rmThenD: "Insight de relacionamento · comunicação",
    rmLater: "Mais tarde — KAI Self · Life",
    rmLaterD: "Insight pessoal · bem-estar",
    buyCta: "Comprar KAI",
    connect: "Conectar carteira",
    amount: "Quantos KAI você quer?",
    est: "Pagamento estimado",
    unit: "Preço unitário",
    payWith: "Pagar com",
    approve: "Aprovar USDG",
    buy: "Comprar",
    buying: "Confirme na carteira…",
    swapBuy: "Converter e comprar",
    swapping: "Convertendo para USDG…",
    bridging: "Ponte em andamento…",
    swapUniswap:
      "O swap automático de ETH reverte on-chain. Use MetaMask Swap ou Uniswap (ETH→USDG) e compre com USDG.",
    openUniswap: "ETH → USDG no Uniswap",
    saleWait: "Aguardando a chain",
    saleWaitHint: "A venda está aberta on-chain.",
    saleClosed: "Venda encerrada",
    belowMin: "Compra mínima equivalente a 1 $.",
    noWallet: "Nenhuma carteira. Instale o MetaMask.",
    usdgBal: "Saldo USDG",
    payBal: "Ativo selecionado",
    yourBought: "Comprado nesta carteira",
    cap: "Teto por carteira",
    txOk: "Compra registrada. KAI chega na carteira no TGE.",
    txFail: "Transação falhou ou foi rejeitada",
    needBal: "Saldo insuficiente neste ativo",
    rounds: "Rodadas",
    roundsLead: "Quatro rodadas a preço fixo. Cada tranche usa o preço da sua rodada.",
    tokenomics: "Tokenomia",
    supply: "Oferta total fixa",
    supplyLine: "O teto da pré-venda está travado no contrato.",
    how: "Como comprar",
    step1: "Conecte uma carteira",
    step1d: "MetaMask. Rede: Robinhood Chain (4663).",
    step2: "Pague com USDG",
    step2d: "USDG na Robinhood? Compre direto. Primeiro troque ETH→USDG.",
    step3: "Digite o valor e assine",
    step3d: "Aprovar + comprar na sua carteira. Mínimo 1 $.",
    product: "KindredHQ.io",
    open: "Venda aberta",
    pending: "Pendente",
    everyone: "Aberto a todos",
    tge: "15 % no TGE; o restante linear em 18 meses.",
    teamVest: "Equipe: 0 % TGE, cliff de 12 meses, linear 60 meses.",
    contracts: "Contratos",
    overview: "Visão geral",
    footerChain: "Emitido na Robinhood Chain.",
    allocPresale: "Pré-venda",
    allocEco: "Ecossistema e recompensas Kai",
    allocTreasury: "Tesouraria / produto",
    allocLiquidity: "Liquidez",
    allocMarketing: "Marketing",
    allocTeam: "Equipe",
    allocCommunity: "Comunidade",
    allocAdvisors: "Conselheiros",
  },
  ru: {
    brand: "KindredHQ",
    kicker: "Пресейл KAI",
    heroTitle: "Пусть встречаются души, а не лица.",
    heroTagline: "Утилити-токен KindredHQ — в сети Robinhood Chain.",
    heroBody:
      "KindredHQ — живой продукт знакомств без фото. Kai узнаёт вас в разговоре. $KAI не спекулятивная обёртка: им оплачивают кредиты Kai, премиум-доступ и сервисы экосистемы.",
    chainBadge: "Robinhood Chain · 4663",
    chainHint:
      "KAI — ERC-20 в сети Robinhood Chain (4663). Газ — ETH, расчёт — USDG. Активы с других сетей сначала попадают сюда.",
    whatHq: "Что такое KindredHQ?",
    whatHqBody: "Знакомства без фото. Люди встречаются из‑за того, кто они. Один матч за раз.",
    whatKai: "Что такое Kai?",
    whatKaiBody: "ИИ-гид, который узнаёт вас в чате — слой, на котором построен продукт.",
    whyToken: "Зачем $KAI?",
    whyTokenBody:
      "Утилити-слой экосистемы. Крипто знать не нужно: оплата → кредиты Kai → продукт. Это не доля и не право на выручку.",
    utilityTitle: "Роль в экосистеме",
    utilityLead: "Эмиссия фиксирована. Токен нужен, чтобы продукт работал — не чтобы обещать доход.",
    util1: "Кредиты Kai — чат и матчинг.",
    util2: "Premium Kai — более глубокая совместимость.",
    util3: "Награды экосистемы — приглашения и вклад.",
    util4: "Партнёры — сервисы, подключённые к Kai.",
    proofTitle: "Продукт сегодня",
    proof1: "Платформа в эфире",
    proof2: "Чат Kai в эфире",
    proof3: "Матчинг работает",
    proof4: "Постепенное открытие",
    roadmap: "Дорожная карта",
    rmNow: "Сейчас — KAI Match",
    rmNowD: "Совместимость · разговор · один матч",
    rmNext: "Дальше",
    rmNextD: "Кредиты Kai · рост · мобильное",
    rmThen: "Затем — KAI Relationship",
    rmThenD: "Инсайт отношений · коммуникация",
    rmLater: "Позже — KAI Self · Life",
    rmLaterD: "Личный инсайт · благополучие",
    buyCta: "Купить KAI",
    connect: "Подключить кошелёк",
    amount: "Сколько KAI вы хотите?",
    est: "Оценка платежа",
    unit: "Цена за единицу",
    payWith: "Оплата",
    approve: "Разрешить USDG",
    buy: "Купить",
    buying: "Подтвердите в кошельке…",
    swapBuy: "Обменять и купить",
    swapping: "Обмен в USDG…",
    bridging: "Мост выполняется…",
    swapUniswap:
      "Автообмен ETH падает в сети. Сделайте ETH→USDG в MetaMask Swap или Uniswap, затем купите за USDG.",
    openUniswap: "ETH → USDG на Uniswap",
    saleWait: "Ожидание сети",
    saleWaitHint: "Продажа открыта в сети.",
    saleClosed: "Продажа закрыта",
    belowMin: "Минимальная покупка — эквивалент 1 $.",
    noWallet: "Кошелёк не найден. Установите MetaMask.",
    usdgBal: "Баланс USDG",
    payBal: "Выбранный актив",
    yourBought: "Куплено с этого кошелька",
    cap: "Потолок кошелька",
    txOk: "Покупка записана. KAI придёт в кошелёк на TGE.",
    txFail: "Транзакция не удалась или отклонена",
    needBal: "Недостаточно баланса в этом активе",
    rounds: "Раунды",
    roundsLead: "Четыре раунда с фиксированной ценой. Каждый транш — по цене своего раунда.",
    tokenomics: "Токеномика",
    supply: "Общая эмиссия фиксирована",
    supplyLine: "Потолок пресейла зафиксирован в контракте.",
    how: "Как купить",
    step1: "Подключите кошелёк",
    step1d: "MetaMask. Сеть: Robinhood Chain (4663).",
    step2: "Платите USDG",
    step2d: "Есть USDG в Robinhood — покупайте сразу. Сначала обменяйте ETH→USDG.",
    step3: "Введите сумму и подпишите",
    step3d: "Approve + покупка в вашем кошельке. Минимум 1 $.",
    product: "KindredHQ.io",
    open: "Продажа открыта",
    pending: "Ожидание",
    everyone: "Открыто для всех",
    tge: "15 % на TGE, остальное линейно за 18 месяцев.",
    teamVest: "Команда: 0 % TGE, клифф 12 месяцев, линейно 60 месяцев.",
    contracts: "Контракты",
    overview: "Обзор",
    footerChain: "Выпущен в сети Robinhood Chain.",
    allocPresale: "Пресейл",
    allocEco: "Экосистема и награды Kai",
    allocTreasury: "Казначейство / продукт",
    allocLiquidity: "Ликвидность",
    allocMarketing: "Маркетинг",
    allocTeam: "Команда",
    allocCommunity: "Сообщество",
    allocAdvisors: "Советники",
  },
};

export const ALLOC_KEYS = [
  "allocPresale",
  "allocEco",
  "allocTreasury",
  "allocLiquidity",
  "allocMarketing",
  "allocTeam",
  "allocCommunity",
  "allocAdvisors",
] as const;

export const KPI_PRESALE: Record<Lang, string> = {
  tr: "Ön satış tavanı",
  en: "Presale cap",
  de: "Vorverkaufslimit",
  es: "Tope de preventa",
  fr: "Plafond de prévente",
  it: "Cap prevendita",
  pt: "Teto da pré-venda",
  ru: "Потолок пресейла",
};

