export type Lang = "tr" | "en";

export const copy = {
  tr: {
    brand: "KindredHQ",
    kicker: "KAI ön satış",
    heroTitle: "Yüzler değil, ruhlar tanışsın.",
    heroTagline:
      "KindredHQ’nun yardımcı tokenı. Sabit arz, şeffaf tur yapısı, kişisel bilgi istenmeden katılım.",
    heroBody:
      "KindredHQ fotoğrafsız çalışan bir tanışma ürünüdür ve yayındadır. Liste yok, kaydırma yok. Kai, sohbetle tanır; kime neden uyduğunu gerekçesiyle söyler. $KAI bu katmanın kullanım tokenıdır.",
    whatHq: "KindredHQ nedir?",
    whatHqBody:
      "Fotoğrafsız tanışma platformu. İnsanları görünüşle değil, kim olduklarıyla eşleştirir. Her seferinde tek eşleşme; gizlilik öncelikli.",
    whatKai: "Kai nedir?",
    whatKaiBody:
      "Kullanıcıyı anketle değil sohbetle tanıyan yapay zeka rehberi. Bir özellik değil; ürünün üzerine kurulduğu katman.",
    whyToken: "$KAI neden var?",
    whyTokenBody:
      "Kai ekosisteminin fayda katmanı. Günlük kullanıcı kripto bilmek zorunda değil: normal ödeme → Kai Kredisi → hizmet.",
    utilityTitle: "$KAI ne işe yarar",
    util1: "Kai Kredileri — sohbet ve eşleşme erişimi.",
    util2: "Premium Kai — daha derin uyum içgörüleri.",
    util3: "Ekosistem ödülleri — davet ve topluluk katkısı.",
    util4: "İş ortakları — Kai’ye bağlanan hizmetler.",
    proofTitle: "Ürün şu an",
    proof1: "Platform yayında",
    proof2: "Kai sohbeti canlı",
    proof3: "Uyum ve eşleştirme çalışıyor",
    proof4: "Kademeli açılma (ses ve yüz zamanla)",
    roadmap: "Yol haritası",
    rmNow: "Şimdi — KAI Match",
    rmNowD: "Yapay zeka uyum · sohbetle tanıma · her seferinde tek eşleşme",
    rmNext: "Sırada",
    rmNextD: "Kai Kredileri · küresel büyüme · mobil · ekosistem hazırlığı",
    rmThen: "Ardından — KAI Relationship",
    rmThenD: "İlişki içgörüleri · iletişim desteği · çift değerlendirmeleri",
    rmLater: "Sonra — KAI Self · KAI Life",
    rmLaterD: "Kişisel içgörü · esenlik · yaşam araçları",
    buyCta: "KAI al",
    connect: "Cüzdan bağla",
    connecting: "Bağlanıyor…",
    switchNet: "Robinhood Chain’e geç",
    disconnect: "Ayır",
    amount: "Kaç KAI almak istiyorsun?",
    est: "Tahmini ödeme",
    unit: "Birim fiyat",
    payWith: "Öde",
    approve: "USDG onayla",
    buy: "Satın al",
    buying: "Cüzdanda onayla…",
    swapBuy: "Çevir ve al",
    swapping: "USDG’ye çevriliyor…",
    bridging: "Köprü tamamlanıyor…",
    swapUniswap:
      "ETH otomatik çeviri şu an zincirde düşüyor. MetaMask Takas veya Uniswap ile ETH→USDG yap, sonra USDG ile al.",
    openUniswap: "Uniswap’te ETH → USDG",
    saleWait: "Zincir onayı bekleniyor",
    saleWaitHint: "Satış zincirde açık.",
    saleClosed: "Satış kapandı",
    belowMin: "En az 1 $ karşılığı alım yapılabilir.",
    noWallet: "Tarayıcıda cüzdan bulunamadı. MetaMask yükle.",
    connected: "Bağlı",
    usdgBal: "USDG bakiyen",
    payBal: "Seçilen varlık",
    yourBought: "Bu cüzdandan alınan",
    cap: "Cüzdan tavanı",
    txOk: "Alım kaydedildi. KAI TGE’de cüzdana gelir.",
    txFail: "İşlem başarısız veya reddedildi",
    needBal: "Bu varlıkta yeterli bakiye yok",
    wrongNet: "Yanlış ağ",
    rounds: "Turlar",
    roundsLead:
      "Dört tur, fiyat sabit. Alım turları aşarsa her dilim kendi fiyatından hesaplanır.",
    tokenomics: "Token ekonomisi",
    supply: "Toplam arz sabit",
    supplyLine: "Ön satış tavanı aşılamaz; rakamlar kontrat parametreleridir.",
    how: "Nasıl alınır",
    step1: "Cüzdanını bağla",
    step1d: "MetaMask. Ağ: Robinhood Chain.",
    step2: "USDG ile al — en kolayı",
    step2d:
      "Robinhood’da USDG varsa doğrudan al. ETH’yi MetaMask Takas ile USDG yap. USDT/USDC başka ağdaysa köprülenir.",
    step3: "Miktarı yaz ve imzala",
    step3d: "Onay + alım senin cüzdanında. Minimum 1 $.",
    product: "KindredHQ.io",
    open: "Satış açık",
    pending: "İmza bekleniyor",
    everyone: "Herkes katılabilir",
    tge: "TGE’de %15 açılır, kalanı 18 ay doğrusal.",
    teamVest: "Ekip: TGE %0, 12 ay bekler, 60 ay doğrusal.",
    contracts: "Kontratlar",
    overview: "Genel bakış",
    lang: "EN",
  },
  en: {
    brand: "KindredHQ",
    kicker: "KAI presale",
    heroTitle: "Let souls meet, not faces.",
    heroTagline:
      "KindredHQ’s utility token. Fixed supply, transparent rounds, no personal data required.",
    heroBody:
      "KindredHQ is a live, photo-free matching product. No grid, no swipe. Kai learns you through conversation and explains why a match fits. $KAI is the utility layer for that product.",
    whatHq: "What is KindredHQ?",
    whatHqBody:
      "A photo-free matching platform. People meet for who they are, not how they look. One match at a time; privacy first.",
    whatKai: "What is Kai?",
    whatKaiBody:
      "An AI guide that learns you through chat, not a survey. Not a feature — the layer the product is built on.",
    whyToken: "Why $KAI?",
    whyTokenBody:
      "The utility layer of the Kai ecosystem. Everyday users don’t need crypto: pay normally → Kai Credits → use the product.",
    utilityTitle: "What $KAI is for",
    util1: "Kai Credits — chat and matching access.",
    util2: "Premium Kai — deeper compatibility insight.",
    util3: "Ecosystem rewards — invites and contribution.",
    util4: "Partners — services that plug into Kai.",
    proofTitle: "The product today",
    proof1: "Platform is live",
    proof2: "Kai chat is live",
    proof3: "Matching infrastructure is running",
    proof4: "Gradual unlock (voice and face over time)",
    roadmap: "Roadmap",
    rmNow: "Now — KAI Match",
    rmNowD: "AI compatibility · conversation-first · one match at a time",
    rmNext: "Next",
    rmNextD: "Kai Credits · growth · mobile · ecosystem prep",
    rmThen: "Then — KAI Relationship",
    rmThenD: "Relationship insight · communication support · couple reviews",
    rmLater: "Later — KAI Self · KAI Life",
    rmLaterD: "Personal insight · wellbeing · life tools",
    buyCta: "Buy KAI",
    connect: "Connect wallet",
    connecting: "Connecting…",
    switchNet: "Switch to Robinhood Chain",
    disconnect: "Disconnect",
    amount: "How much KAI do you want?",
    est: "Estimated payment",
    unit: "Unit price",
    payWith: "Pay with",
    approve: "Approve USDG",
    buy: "Buy",
    buying: "Confirm in wallet…",
    swapBuy: "Swap and buy",
    swapping: "Swapping to USDG…",
    bridging: "Bridge in progress…",
    swapUniswap:
      "Automatic ETH swap is reverting on-chain. Use MetaMask Swap or Uniswap (ETH→USDG), then buy with USDG.",
    openUniswap: "ETH → USDG on Uniswap",
    saleWait: "Waiting on-chain",
    saleWaitHint: "The sale is open on-chain.",
    saleClosed: "Sale closed",
    belowMin: "Minimum purchase is $1 equivalent.",
    noWallet: "No wallet found. Install MetaMask.",
    connected: "Connected",
    usdgBal: "USDG balance",
    payBal: "Selected asset",
    yourBought: "Bought from this wallet",
    cap: "Wallet cap",
    txOk: "Purchase recorded. KAI arrives in-wallet at TGE.",
    txFail: "Transaction failed or rejected",
    needBal: "Not enough balance in this asset",
    wrongNet: "Wrong network",
    rounds: "Rounds",
    roundsLead:
      "Four rounds at fixed prices. If a buy spans rounds, each tranche uses its own price.",
    tokenomics: "Token economics",
    supply: "Total supply is fixed",
    supplyLine: "The presale cap cannot be exceeded; figures are contract parameters.",
    how: "How to buy",
    step1: "Connect a wallet",
    step1d: "MetaMask. Network: Robinhood Chain.",
    step2: "USDG is the easy path",
    step2d:
      "If you hold USDG on Robinhood, buy directly. Swap ETH→USDG in MetaMask. USDT/USDC on other chains can be bridged.",
    step3: "Enter an amount and sign",
    step3d: "Approve + buy in your wallet. Minimum $1.",
    product: "KindredHQ.io",
    open: "Sale open",
    pending: "Signature pending",
    everyone: "Open to everyone",
    tge: "15% at TGE, remainder linear over 18 months.",
    teamVest: "Team: 0% at TGE, 12-month cliff, 60 months linear.",
    contracts: "Contracts",
    overview: "Overview",
    lang: "TR",
  },
} as const;
