export type Lang = "tr" | "en";

export const copy = {
  tr: {
    brand: "KindredHQ",
    kicker: "KAI ön satış",
    heroTitle: "Yüzler değil, ruhlar tanışsın.",
    heroBody:
      "KindredHQ canlı bir tanışma ürünü. $KAI bu ekosistemin kullanım katmanı. Allowlist yok — cüzdanı olan herkes katılabilir.",
    buyCta: "KAI al",
    connect: "Cüzdan bağla",
    connecting: "Bağlanıyor…",
    switchNet: "Robinhood Chain’e geç",
    disconnect: "Ayır",
    amount: "Kaç KAI almak istiyorsun?",
    est: "Tahmini ödeme",
    unit: "Birim fiyat",
    payWith: "Öde",
    approve: "USDG onayla",
    buy: "Satın al",
    buying: "Cüzdanda onayla…",
    swapBuy: "Çevir ve al",
    swapping: "USDG’ye çevriliyor…",
    bridging: "Köprü tamamlanıyor…",
    saleWait: "Zincir onayı bekleniyor",
    saleWaitHint: "Satış zincirde açık. Cüzdanı bağla ve al.",
    saleClosed: "Satış kapandı",
    belowMin: "Minimum alım $10 karşılığı.",
    noWallet: "Tarayıcıda cüzdan bulunamadı. MetaMask veya benzeri bir cüzdan yükle.",
    connected: "Bağlı",
    usdgBal: "USDG bakiyen",
    payBal: "Seçilen varlık",
    yourBought: "Bu cüzdandan alınan",
    cap: "Cüzdan tavanı",
    txOk: "Alım kaydedildi. KAI TGE’de cüzdana gelir.",
    txFail: "İşlem başarısız veya reddedildi",
    needBal: "Bu varlıkta yeterli bakiye yok",
    wrongNet: "Yanlış ağ",
    rounds: "Turlar",
    roundsLead:
      "Dört tur, her birinin fiyatı sabit. Alım turları aşarsa her dilim kendi fiyatından hesaplanır.",
    tokenomics: "Token ekonomisi",
    supply: "Toplam arz sabit",
    how: "Nasıl alınır",
    step1: "Cüzdanını bağla",
    step1d: "MetaMask veya enjekte cüzdan. Ağ: Robinhood Chain.",
    step2: "USDT, USDC, ETH veya USDG",
    step2d:
      "USDG ile doğrudan al. ETH / USDT / USDC seçersen önce USDG’ye çevrilir, sonra KAI alınır.",
    step3: "Miktarı yaz ve imzala",
    step3d: "Her imza senin cüzdanında. Site senin adına işlem atamaz.",
    product: "KindredHQ.io",
    open: "Satış açık",
    pending: "İmza bekleniyor",
    everyone: "Herkes katılabilir",
    tge: "TGE’de %15 açılır, kalanı 18 ay doğrusal.",
    teamVest: "Ekip: TGE %0, 12 ay bekler, 60 ay doğrusal.",
    contracts: "Kontratlar",
    lang: "EN",
  },
  en: {
    brand: "KindredHQ",
    kicker: "KAI presale",
    heroTitle: "Let souls meet, not faces.",
    heroBody:
      "KindredHQ is a live matching product. $KAI is its utility layer. No allowlist — any wallet can join.",
    buyCta: "Buy KAI",
    connect: "Connect wallet",
    connecting: "Connecting…",
    switchNet: "Switch to Robinhood Chain",
    disconnect: "Disconnect",
    amount: "How much KAI do you want?",
    est: "Estimated payment",
    unit: "Unit price",
    payWith: "Pay with",
    approve: "Approve USDG",
    buy: "Buy",
    buying: "Confirm in wallet…",
    swapBuy: "Swap and buy",
    swapping: "Swapping to USDG…",
    bridging: "Bridge in progress…",
    saleWait: "Waiting on-chain",
    saleWaitHint: "The sale is open on-chain. Connect and buy.",
    saleClosed: "Sale closed",
    belowMin: "Minimum purchase is $10 equivalent.",
    noWallet: "No wallet found. Install MetaMask or another injected wallet.",
    connected: "Connected",
    usdgBal: "USDG balance",
    payBal: "Selected asset",
    yourBought: "Bought from this wallet",
    cap: "Wallet cap",
    txOk: "Purchase recorded. KAI arrives in-wallet at TGE.",
    txFail: "Transaction failed or rejected",
    needBal: "Not enough balance in this asset",
    wrongNet: "Wrong network",
    rounds: "Rounds",
    roundsLead:
      "Four rounds, each at a fixed price. If a buy spans rounds, each tranche is priced on its own round.",
    tokenomics: "Token economics",
    supply: "Total supply is fixed",
    how: "How to buy",
    step1: "Connect a wallet",
    step1d: "MetaMask or any injected wallet. Network: Robinhood Chain.",
    step2: "USDT, USDC, ETH or USDG",
    step2d:
      "Pay with USDG directly. ETH / USDT / USDC are swapped to USDG first, then KAI is bought.",
    step3: "Enter an amount and sign",
    step3d: "Every signature is in your wallet. This site never sends a tx for you.",
    product: "KindredHQ.io",
    open: "Sale open",
    pending: "Signature pending",
    everyone: "Open to everyone",
    tge: "15% at TGE, remainder linear over 18 months.",
    teamVest: "Team: 0% at TGE, 12-month cliff, 60 months linear.",
    contracts: "Contracts",
    lang: "TR",
  },
} as const;
